
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 06 21:02:43 CET 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHTCURLYBR = 19;
  public static final int LEFTCURLYBR = 18;
  public static final int SEMICOLON = 21;
  public static final int ELSE = 8;
  public static final int INT = 3;
  public static final int EQUAL = 12;
  public static final int NOTEQUAL = 13;
  public static final int LEFTPAR = 16;
  public static final int MOREOREQUAL = 15;
  public static final int INTCONST = 22;
  public static final int RIGHTPAR = 17;
  public static final int IF = 6;
  public static final int COLON = 20;
  public static final int ID = 25;
  public static final int LESSOREQUAL = 11;
  public static final int BOOLEAN = 5;
  public static final int EOF = 0;
  public static final int REALCONST = 23;
  public static final int MORE = 14;
  public static final int MAIN = 2;
  public static final int ELIF = 7;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int REAL = 4;
  public static final int BOOLCONST = 24;
  public static final int LESS = 10;
}

