// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: C:/EclipseProgPrev/PP_Lab2/src/spec.flex

// KORISNICKI KOD


@SuppressWarnings("fallthrough")
class Lab2NR19347 {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int KOMENTAR = 2;
  public static final int INT_OSNOVA_2 = 4;
  public static final int INT_OSNOVA_3 = 6;
  public static final int INT_OSNOVA_4 = 8;
  public static final int INT_OSNOVA_5 = 10;
  public static final int INT_OSNOVA_6 = 12;
  public static final int INT_OSNOVA_7 = 14;
  public static final int INT_OSNOVA_8 = 16;
  public static final int INT_OSNOVA_9 = 18;
  public static final int INT_OSNOVA_10 = 20;
  public static final int INT_OSNOVA_11 = 22;
  public static final int INT_OSNOVA_12 = 24;
  public static final int INT_OSNOVA_13 = 26;
  public static final int INT_OSNOVA_14 = 28;
  public static final int INT_OSNOVA_15 = 30;
  public static final int INT_OSNOVA_16 = 32;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 
    16, 16
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\2\0"+
    "\1\4\4\0\1\5\1\6\1\7\1\10\1\0\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\2\0\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\24\40\6\0\1\41\1\33\1\34\1\35\1\42\1\43"+
    "\5\40\1\44\5\40\1\45\1\46\1\47\1\50\5\40"+
    "\1\51\1\0\1\52\7\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\21\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\12\7\1\10\1\11\1\12\1\1\1\13\3\14\1\15"+
    "\1\16\1\0\1\17\1\20\1\21\1\20\1\22\1\20"+
    "\1\23\1\20\1\24\1\20\1\25\1\20\1\26\1\20"+
    "\1\27\1\20\1\30\1\20\1\31\1\20\1\32\1\20"+
    "\1\33\1\20\1\34\1\20\1\35\1\20\1\36\1\20"+
    "\1\0\10\7\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\2\14\1\55\1\56\1\0\1\57\1\60\1\61\1\62"+
    "\1\63\1\64\2\14\1\0\2\7";

  private static int [] zzUnpackAction() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\u012d"+
    "\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a\0\u0285"+
    "\0\u02b0\0\u02db\0\u02db\0\u02db\0\u02db\0\u02db\0\u02db\0\u0306"+
    "\0\u0331\0\u035c\0\u0387\0\u03b2\0\u03dd\0\u0408\0\u0433\0\u045e"+
    "\0\u0489\0\u04b4\0\u04df\0\u02db\0\u050a\0\u0535\0\u0560\0\u058b"+
    "\0\u05b6\0\u05e1\0\u02db\0\u02db\0\u060c\0\u02db\0\u0637\0\u02db"+
    "\0\u0662\0\u02db\0\u068d\0\u02db\0\u06b8\0\u02db\0\u06e3\0\u02db"+
    "\0\u070e\0\u02db\0\u0739\0\u02db\0\u0764\0\u02db\0\u078f\0\u02db"+
    "\0\u07ba\0\u02db\0\u07e5\0\u02db\0\u0810\0\u02db\0\u083b\0\u02db"+
    "\0\u0866\0\u02db\0\u0891\0\u08bc\0\u08e7\0\u0912\0\u093d\0\u0968"+
    "\0\u0993\0\u09be\0\u09e9\0\u0a14\0\u02db\0\u02db\0\u02db\0\u02db"+
    "\0\u02db\0\u02db\0\u02db\0\u02db\0\u02db\0\u02db\0\u02db\0\u02db"+
    "\0\u02db\0\u0a3f\0\u0a6a\0\u0a95\0\u02db\0\u02db\0\u0ac0\0\u02db"+
    "\0\u02db\0\u02db\0\u02db\0\u02db\0\u02db\0\u0aeb\0\u0b16\0\u0b41"+
    "\0\u0b41\0\u058b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\22\2\23\1\0\1\24\1\25\1\26\1\27\2\22"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\11\50\1\51\3\50\1\52\1\50\1\53\1\54\7\2"+
    "\1\55\43\2\2\56\2\0\7\56\2\57\36\56\2\60"+
    "\2\0\7\60\3\61\35\60\2\62\2\0\7\62\4\63"+
    "\34\62\2\64\2\0\7\64\5\65\33\64\2\66\2\0"+
    "\7\66\6\67\32\66\2\70\2\0\7\70\7\71\31\70"+
    "\2\72\2\0\7\72\10\73\30\72\2\74\2\0\7\74"+
    "\11\75\27\74\2\76\2\0\7\76\12\77\26\76\2\100"+
    "\2\0\7\100\12\101\5\100\1\101\6\100\1\101\11\100"+
    "\2\102\2\0\7\102\12\103\5\102\2\103\5\102\1\103"+
    "\11\102\2\104\2\0\7\104\12\105\5\104\3\105\4\104"+
    "\1\105\11\104\2\106\2\0\7\106\12\107\5\106\4\107"+
    "\3\106\1\107\11\106\2\110\2\0\7\110\12\111\5\110"+
    "\5\111\2\110\2\111\10\110\2\112\2\0\7\112\12\113"+
    "\5\112\6\113\1\112\3\113\7\112\62\0\1\114\54\0"+
    "\1\115\1\0\12\31\37\0\1\115\1\0\1\116\1\117"+
    "\1\120\1\121\1\122\1\123\1\124\3\31\32\0\1\125"+
    "\4\0\1\115\1\0\12\31\32\0\1\126\4\0\1\115"+
    "\1\0\12\31\32\0\1\127\4\0\1\115\1\0\12\31"+
    "\32\0\1\130\4\0\1\115\1\0\12\31\32\0\1\131"+
    "\4\0\1\115\1\0\12\31\32\0\1\132\4\0\1\115"+
    "\1\0\12\31\32\0\1\133\4\0\1\115\1\0\12\31"+
    "\32\0\1\134\4\0\1\115\1\0\12\31\56\0\1\135"+
    "\52\0\1\136\1\137\51\0\1\140\52\0\1\141\35\0"+
    "\12\142\5\0\17\50\15\0\12\142\5\0\7\50\1\143"+
    "\7\50\15\0\12\142\5\0\13\50\1\144\3\50\2\0"+
    "\7\2\1\55\2\2\1\145\40\2\13\0\2\57\51\0"+
    "\3\61\50\0\4\63\47\0\5\65\46\0\6\67\45\0"+
    "\7\71\44\0\10\73\43\0\11\75\42\0\12\77\41\0"+
    "\12\101\5\0\1\101\6\0\1\101\24\0\12\103\5\0"+
    "\2\103\5\0\1\103\24\0\12\105\5\0\3\105\4\0"+
    "\1\105\24\0\12\107\5\0\4\107\3\0\1\107\24\0"+
    "\12\111\5\0\5\111\2\0\2\111\23\0\12\113\5\0"+
    "\6\113\1\0\3\113\16\0\1\146\56\0\12\115\11\0"+
    "\1\147\20\0\1\150\4\0\1\115\1\0\12\31\32\0"+
    "\1\151\4\0\1\115\1\0\12\31\32\0\1\152\4\0"+
    "\1\115\1\0\12\31\32\0\1\153\4\0\1\115\1\0"+
    "\12\31\32\0\1\154\4\0\1\115\1\0\12\31\32\0"+
    "\1\155\4\0\1\115\1\0\12\31\32\0\1\24\4\0"+
    "\1\115\1\0\12\31\41\0\12\142\5\0\17\142\15\0"+
    "\12\142\5\0\12\50\1\156\4\50\15\0\12\142\5\0"+
    "\16\50\1\157\12\0\1\160\2\0\12\161\41\0\12\142"+
    "\5\0\14\50\1\157\2\50\15\0\12\142\5\0\10\50"+
    "\1\162\6\50\15\0\12\161\26\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2924];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\21\0\6\11\14\1\1\11\6\1\2\11\1\0\1\11"+
    "\1\1\1\11\1\1\1\11\1\1\1\11\1\1\1\11"+
    "\1\1\1\11\1\1\1\11\1\1\1\11\1\1\1\11"+
    "\1\1\1\11\1\1\1\11\1\1\1\11\1\1\1\11"+
    "\1\1\1\11\1\1\1\11\1\1\1\0\10\1\15\11"+
    "\3\1\2\11\1\0\6\11\2\1\1\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
//Dodatni clan u generisanoj klasi
KWTable kwt = new KWTable();
Yytoken getKW()
{
	return new Yytoken(kwt.find(yytext()), yytext(), yyline, yycolumn);
}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lab2NR19347(java.io.Reader in) {
    this.zzReader = in;
  }


  private static String zzToPrintable(String str) {
    StringBuilder builder = new StringBuilder();
    for (int n = 0 ; n < str.length() ; ) {
      int ch = str.codePointAt(n);
      int charCount = Character.charCount(ch);
      n += charCount;
      if (ch > 31 && ch < 127) {
        builder.append((char)ch);
      } else if (charCount == 1) {
        builder.append(String.format("\\u%04X", ch));
      } else {
        builder.append(String.format("\\U%06X", ch));
      }
    }
    return builder.toString();
  }

  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Yytoken generate_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 	return new Yytoken(sym.HASH, "#", yyline, yycolumn); //Vracam ID za hash kad zavrsi 
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [156] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: \" + yytext() ); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: " + yytext() );
            }
          // fall through
          case 53: break;
          case 2:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [123] { ; }");
            { ;
            }
          // fall through
          case 54: break;
          case 3:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [115] { yybegin(INT_OSNOVA_16); }");
            { yybegin(INT_OSNOVA_16);
            }
          // fall through
          case 55: break;
          case 4:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [124] { return new Yytoken(sym.LEFTPAR, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.LEFTPAR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 56: break;
          case 5:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [125] { return new Yytoken(sym.RIGHTPAR, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.RIGHTPAR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 57: break;
          case 6:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [137] { return new Yytoken(sym.MULTIPLY, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.MULTIPLY, yytext(), yyline, yycolumn);
            }
          // fall through
          case 58: break;
          case 7:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [119] { return new Yytoken(sym.CONST, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.CONST, yytext(), yyline, yycolumn);
            }
          // fall through
          case 59: break;
          case 8:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [129] { return new Yytoken(sym.COLON, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.COLON, yytext(), yyline, yycolumn);
            }
          // fall through
          case 60: break;
          case 9:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [128] { return new Yytoken(sym.SEMICOLON, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.SEMICOLON, yytext(), yyline, yycolumn);
            }
          // fall through
          case 61: break;
          case 10:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [135] { return new Yytoken(sym.LESS, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.LESS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 62: break;
          case 11:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [132] { return new Yytoken(sym.MORE, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.MORE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 63: break;
          case 12:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [147] { return getKW(); }");
            { return getKW();
            }
          // fall through
          case 64: break;
          case 13:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [126] { return new Yytoken(sym.LEFTCURLYBR, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.LEFTCURLYBR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 65: break;
          case 14:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [127] { return new Yytoken(sym.RIGHTCURLYBR, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.RIGHTCURLYBR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 66: break;
          case 15:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [61] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova2\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova2" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 67: break;
          case 16:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [60] { yybegin(YYINITIAL); return new Yytoken(sym.CONST, yytext(), yyline, yycolumn); }");
            { yybegin(YYINITIAL); return new Yytoken(sym.CONST, yytext(), yyline, yycolumn);
            }
          // fall through
          case 68: break;
          case 17:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [65] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova3\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova3" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 69: break;
          case 18:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [69] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova4\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova4" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 70: break;
          case 19:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [73] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova5\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova5" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 71: break;
          case 20:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [77] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova6\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova6" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 72: break;
          case 21:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [81] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova7\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova7" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 73: break;
          case 22:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [85] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova8\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova8" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 74: break;
          case 23:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [89] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR:osnova9\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR:osnova9" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 75: break;
          case 24:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [93] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova10\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova10" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 76: break;
          case 25:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [97] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova11\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova11" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 77: break;
          case 26:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [101] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova12\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova12" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 78: break;
          case 27:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [105] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova13\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova13" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 79: break;
          case 28:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [109] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova14\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova14" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 80: break;
          case 29:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [113] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR: osnova15\" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR: osnova15" + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 81: break;
          case 30:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [117] { if (yytext() != null && yytext().length() > 0) System.out.println( \"ERROR osnova16: \" + yytext() ); yybegin(YYINITIAL); }");
            { if (yytext() != null && yytext().length() > 0) System.out.println( "ERROR osnova16: " + yytext() ); yybegin(YYINITIAL);
            }
          // fall through
          case 82: break;
          case 31:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [59] { yybegin(INT_OSNOVA_2); }");
            { yybegin(INT_OSNOVA_2);
            }
          // fall through
          case 83: break;
          case 32:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [63] { yybegin(INT_OSNOVA_3); }");
            { yybegin(INT_OSNOVA_3);
            }
          // fall through
          case 84: break;
          case 33:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [67] { yybegin(INT_OSNOVA_4); }");
            { yybegin(INT_OSNOVA_4);
            }
          // fall through
          case 85: break;
          case 34:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [71] { yybegin(INT_OSNOVA_5); }");
            { yybegin(INT_OSNOVA_5);
            }
          // fall through
          case 86: break;
          case 35:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [75] { yybegin(INT_OSNOVA_6); }");
            { yybegin(INT_OSNOVA_6);
            }
          // fall through
          case 87: break;
          case 36:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [79] { yybegin(INT_OSNOVA_7); }");
            { yybegin(INT_OSNOVA_7);
            }
          // fall through
          case 88: break;
          case 37:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [83] { yybegin(INT_OSNOVA_8); }");
            { yybegin(INT_OSNOVA_8);
            }
          // fall through
          case 89: break;
          case 38:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [87] { yybegin(INT_OSNOVA_9); }");
            { yybegin(INT_OSNOVA_9);
            }
          // fall through
          case 90: break;
          case 39:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [130] { return new Yytoken(sym.ASSIGN, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.ASSIGN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 91: break;
          case 40:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [134] { return new Yytoken(sym.LESSOREQUAL, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.LESSOREQUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 92: break;
          case 41:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [133] { return new Yytoken(sym.NOTEQUAL, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.NOTEQUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 93: break;
          case 42:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [136] { return new Yytoken(sym.EQUAL, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.EQUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 94: break;
          case 43:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [131] { return new Yytoken(sym.MOREOREQUAL, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.MOREOREQUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 95: break;
          case 44:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [150] { return new Yytoken(sym.ID, yytext(), yyline, yycolumn); }");
            { return new Yytoken(sym.ID, yytext(), yyline, yycolumn);
            }
          // fall through
          case 96: break;
          case 45:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [55] { yybegin(YYINITIAL); }");
            { yybegin(YYINITIAL);
            }
          // fall through
          case 97: break;
          case 46:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [54] { yybegin(KOMENTAR); }");
            { yybegin(KOMENTAR);
            }
          // fall through
          case 98: break;
          case 47:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [91] { yybegin(INT_OSNOVA_10); }");
            { yybegin(INT_OSNOVA_10);
            }
          // fall through
          case 99: break;
          case 48:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [95] { yybegin(INT_OSNOVA_11); }");
            { yybegin(INT_OSNOVA_11);
            }
          // fall through
          case 100: break;
          case 49:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [99] { yybegin(INT_OSNOVA_12); }");
            { yybegin(INT_OSNOVA_12);
            }
          // fall through
          case 101: break;
          case 50:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [103] { yybegin(INT_OSNOVA_13); }");
            { yybegin(INT_OSNOVA_13);
            }
          // fall through
          case 102: break;
          case 51:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [107] { yybegin(INT_OSNOVA_14); }");
            { yybegin(INT_OSNOVA_14);
            }
          // fall through
          case 103: break;
          case 52:
            System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [111] { yybegin(INT_OSNOVA_15); }");
            { yybegin(INT_OSNOVA_15);
            }
          // fall through
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lab2NR19347 [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lab2NR19347 scanner = null;
        java.io.FileInputStream stream = null;
        java.io.Reader reader = null;
        try {
          stream = new java.io.FileInputStream(argv[i]);
          reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lab2NR19347(reader);
          do {
            System.out.println(scanner.generate_token());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
        finally {
          if (reader != null) {
            try {
              reader.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
          if (stream != null) {
            try {
              stream.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
        }
      }
    }
  }


}
