// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20241207210605_V2")]
    partial class V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Bolnica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojOdeljenja")
                        .HasColumnType("int");

                    b.Property<int>("BrojOsoblja")
                        .HasColumnType("int");

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Bolnice");
                });

            modelBuilder.Entity("WebTemplate.Models.BolnicaLekar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BolnicaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumUgovora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LekarID")
                        .HasColumnType("int");

                    b.Property<string>("Specijalnost")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BolnicaID");

                    b.HasIndex("LekarID");

                    b.ToTable("BolnicaLekari");
                });

            modelBuilder.Entity("WebTemplate.Models.Lekar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumDiplomiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LicencaID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LicencaID");

                    b.ToTable("Lekari");
                });

            modelBuilder.Entity("WebTemplate.Models.Licenca", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumDobijanja")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Licence");
                });

            modelBuilder.Entity("WebTemplate.Models.BolnicaLekar", b =>
                {
                    b.HasOne("WebTemplate.Models.Bolnica", "Bolnica")
                        .WithMany("Lekari")
                        .HasForeignKey("BolnicaID");

                    b.HasOne("WebTemplate.Models.Lekar", "Lekar")
                        .WithMany("Bolnice")
                        .HasForeignKey("LekarID");

                    b.Navigation("Bolnica");

                    b.Navigation("Lekar");
                });

            modelBuilder.Entity("WebTemplate.Models.Lekar", b =>
                {
                    b.HasOne("WebTemplate.Models.Licenca", "Licenca")
                        .WithMany()
                        .HasForeignKey("LicencaID");

                    b.Navigation("Licenca");
                });

            modelBuilder.Entity("WebTemplate.Models.Bolnica", b =>
                {
                    b.Navigation("Lekari");
                });

            modelBuilder.Entity("WebTemplate.Models.Lekar", b =>
                {
                    b.Navigation("Bolnice");
                });
#pragma warning restore 612, 618
        }
    }
}
