
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 06 14:19:00 CET 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHTCURLYBR = 21;
  public static final int LEFTCURLYBR = 20;
  public static final int SEMICOLON = 23;
  public static final int ELSE = 8;
  public static final int INT = 3;
  public static final int EQUAL = 14;
  public static final int NOTEQUAL = 15;
  public static final int LEFTPAR = 18;
  public static final int MOREOREQUAL = 17;
  public static final int RIGHTPAR = 19;
  public static final int IF = 6;
  public static final int COLON = 22;
  public static final int ID = 9;
  public static final int LESSOREQUAL = 13;
  public static final int BOOLEAN = 5;
  public static final int EOF = 0;
  public static final int MORE = 16;
  public static final int MAIN = 2;
  public static final int ELIF = 7;
  public static final int CONST = 10;
  public static final int error = 1;
  public static final int ASSIGN = 11;
  public static final int REAL = 4;
  public static final int LESS = 12;
}

