// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(MaratonContext))]
    partial class MaratonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportSportista", b =>
                {
                    b.Property<int>("SportisteID")
                        .HasColumnType("int");

                    b.Property<int>("SportoviID")
                        .HasColumnType("int");

                    b.HasKey("SportisteID", "SportoviID");

                    b.HasIndex("SportoviID");

                    b.ToTable("SportSportista");
                });

            modelBuilder.Entity("WebTemplate.Models.Disciplina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojTakmicara")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumOdKadaPostoji")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Discipline");
                });

            modelBuilder.Entity("WebTemplate.Models.Rekord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DisciplinaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OstvarenDana")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SportistaID")
                        .HasColumnType("int");

                    b.Property<string>("Takmicenje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DisciplinaID");

                    b.HasIndex("SportistaID");

                    b.ToTable("Rekordi");
                });

            modelBuilder.Entity("WebTemplate.Models.Sport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PojavioSe")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Sportovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Sportista", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pol")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Sportisti");
                });

            modelBuilder.Entity("SportSportista", b =>
                {
                    b.HasOne("WebTemplate.Models.Sportista", null)
                        .WithMany()
                        .HasForeignKey("SportisteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebTemplate.Models.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportoviID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebTemplate.Models.Rekord", b =>
                {
                    b.HasOne("WebTemplate.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaID");

                    b.HasOne("WebTemplate.Models.Sportista", "Sportista")
                        .WithMany()
                        .HasForeignKey("SportistaID");

                    b.Navigation("Disciplina");

                    b.Navigation("Sportista");
                });
#pragma warning restore 612, 618
        }
    }
}
