// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20241207164855_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Aerodrom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KapacitetLetelica")
                        .HasColumnType("int");

                    b.Property<int>("KapacitetPutnika")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Aerodromi");
                });

            modelBuilder.Entity("WebTemplate.Models.Let", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojPutnika")
                        .HasColumnType("int");

                    b.Property<int?>("LetelicaID")
                        .HasColumnType("int");

                    b.Property<int>("RelacijaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VremePoletanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremeSletanja")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("LetelicaID");

                    b.HasIndex("RelacijaID");

                    b.ToTable("Letovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Letelica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojMotora")
                        .HasColumnType("int");

                    b.Property<int>("BrojOsoblja")
                        .HasColumnType("int");

                    b.Property<int>("KapacitetPutnika")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Letelice");
                });

            modelBuilder.Entity("WebTemplate.Models.Relacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AerodromDoID")
                        .HasColumnType("int");

                    b.Property<int?>("AerodromOdID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AerodromDoID");

                    b.HasIndex("AerodromOdID");

                    b.ToTable("Relacije");
                });

            modelBuilder.Entity("WebTemplate.Models.Let", b =>
                {
                    b.HasOne("WebTemplate.Models.Letelica", "Letelica")
                        .WithMany()
                        .HasForeignKey("LetelicaID");

                    b.HasOne("WebTemplate.Models.Relacija", "Relacija")
                        .WithMany()
                        .HasForeignKey("RelacijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Letelica");

                    b.Navigation("Relacija");
                });

            modelBuilder.Entity("WebTemplate.Models.Relacija", b =>
                {
                    b.HasOne("WebTemplate.Models.Aerodrom", "AerodromDo")
                        .WithMany()
                        .HasForeignKey("AerodromDoID");

                    b.HasOne("WebTemplate.Models.Aerodrom", "AerodromOd")
                        .WithMany()
                        .HasForeignKey("AerodromOdID");

                    b.Navigation("AerodromDo");

                    b.Navigation("AerodromOd");
                });
#pragma warning restore 612, 618
        }
    }
}
