// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20241207184419_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.DP", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DPovi");
                });

            modelBuilder.Entity("WebTemplate.Models.DPPotrosac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojBrojila")
                        .HasColumnType("int");

                    b.Property<int>("DPID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumPotpisivanjaUgovora")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnickiBroj")
                        .HasColumnType("int");

                    b.Property<int>("PotrosacID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DPID");

                    b.HasIndex("PotrosacID");

                    b.ToTable("Ugovori");
                });

            modelBuilder.Entity("WebTemplate.Models.Elektrodistribucija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojRadnika")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Elektrodistribucije");
                });

            modelBuilder.Entity("WebTemplate.Models.Potrosac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("GodinaRodjenja")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MestoRodjenja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Potrosaci");
                });

            modelBuilder.Entity("WebTemplate.Models.DPPotrosac", b =>
                {
                    b.HasOne("WebTemplate.Models.DP", "DP")
                        .WithMany()
                        .HasForeignKey("DPID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebTemplate.Models.Potrosac", "Potrosac")
                        .WithMany("DPovi")
                        .HasForeignKey("PotrosacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DP");

                    b.Navigation("Potrosac");
                });

            modelBuilder.Entity("WebTemplate.Models.Potrosac", b =>
                {
                    b.Navigation("DPovi");
                });
#pragma warning restore 612, 618
        }
    }
}
