
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 12 16:08:16 CET 2026
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.10k generated parser.
  * @version Mon Jan 12 16:08:16 CET 2026
  */
public class MPParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MPParser() {super();}

  /** Constructor which sets the default scanner. */
  public MPParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\072\000\002\003\006\000\002\002\004\000\002\003" +
    "\006\000\002\003\006\000\002\003\006\000\002\003\006" +
    "\000\002\004\006\000\002\004\006\000\002\004\006\000" +
    "\002\004\006\000\002\005\004\000\002\005\003\000\002" +
    "\007\005\000\002\007\005\000\002\007\004\000\002\007" +
    "\005\000\002\010\003\000\002\010\003\000\002\010\003" +
    "\000\002\006\005\000\002\006\005\000\002\006\003\000" +
    "\002\011\003\000\002\011\003\000\002\013\011\000\002" +
    "\013\011\000\002\013\011\000\002\013\011\000\002\013" +
    "\011\000\002\015\004\000\002\015\003\000\002\015\003" +
    "\000\002\015\002\000\002\016\004\000\002\016\003\000" +
    "\002\020\010\000\002\020\010\000\002\020\010\000\002" +
    "\020\010\000\002\020\010\000\002\020\010\000\002\017" +
    "\005\000\002\017\005\000\002\017\005\000\002\014\005" +
    "\000\002\014\005\000\002\014\003\000\002\021\003\000" +
    "\002\021\003\000\002\022\003\000\002\022\003\000\002" +
    "\022\003\000\002\022\003\000\002\022\003\000\002\022" +
    "\003\000\002\012\005\000\002\012\005\000\002\012\005" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\170\000\006\003\005\004\006\001\002\000\004\002" +
    "\172\001\002\000\004\024\167\001\002\000\006\003\007" +
    "\024\010\001\002\000\004\025\165\001\002\000\006\003" +
    "\012\025\011\001\002\000\006\003\163\026\014\001\002" +
    "\000\004\026\014\001\002\000\004\002\ufffd\001\002\000" +
    "\012\003\016\005\022\006\020\007\021\001\002\000\006" +
    "\003\160\013\157\001\002\000\006\010\030\013\153\001" +
    "\002\000\016\003\ufff6\005\ufff6\006\ufff6\007\ufff6\010\ufff6" +
    "\013\ufff6\001\002\000\006\003\ufff0\013\ufff0\001\002\000" +
    "\006\003\uffef\013\uffef\001\002\000\006\003\ufff1\013\ufff1" +
    "\001\002\000\016\003\033\005\022\006\020\007\021\010" +
    "\030\013\032\001\002\000\010\003\uffeb\027\uffeb\031\uffeb" +
    "\001\002\000\016\003\ufff7\005\ufff7\006\ufff7\007\ufff7\010" +
    "\ufff7\013\ufff7\001\002\000\010\003\147\027\150\031\146" +
    "\001\002\000\010\003\uffea\027\uffea\031\uffea\001\002\000" +
    "\006\003\046\024\047\001\002\000\010\003\uffec\027\uffec" +
    "\031\uffec\001\002\000\006\003\037\015\040\001\002\000" +
    "\006\013\034\027\035\001\002\000\004\031\036\001\002" +
    "\000\016\002\ufffa\003\ufffa\011\ufffa\012\ufffa\027\ufffa\031" +
    "\ufffa\001\002\000\016\003\ufff2\005\ufff2\006\ufff2\007\ufff2" +
    "\010\ufff2\013\ufff2\001\002\000\006\013\041\014\042\001" +
    "\002\000\010\003\044\013\041\014\042\001\002\000\026" +
    "\003\uffd2\016\uffd2\017\uffd2\020\uffd2\021\uffd2\022\uffd2\023" +
    "\uffd2\025\uffd2\027\uffd2\031\uffd2\001\002\000\026\003\uffd1" +
    "\016\uffd1\017\uffd1\020\uffd1\021\uffd1\022\uffd1\023\uffd1\025" +
    "\uffd1\027\uffd1\031\uffd1\001\002\000\010\003\uffca\027\uffca" +
    "\031\uffca\001\002\000\010\003\uffc9\027\uffc9\031\uffc9\001" +
    "\002\000\010\003\uffc8\027\uffc8\031\uffc8\001\002\000\006" +
    "\013\041\014\042\001\002\000\010\003\052\013\041\014" +
    "\042\001\002\000\004\025\130\001\002\000\022\003\uffd3" +
    "\016\123\017\122\020\121\021\124\022\125\023\120\025" +
    "\uffd3\001\002\000\004\025\053\001\002\000\004\030\054" +
    "\001\002\000\004\026\014\001\002\000\014\003\uffe1\011" +
    "\062\012\060\027\uffe1\031\uffe1\001\002\000\014\003\uffe3" +
    "\011\062\012\060\027\uffe3\031\uffe3\001\002\000\010\003" +
    "\uffe6\027\uffe6\031\uffe6\001\002\000\006\003\110\030\111" +
    "\001\002\000\010\003\uffe2\027\uffe2\031\uffe2\001\002\000" +
    "\006\003\064\024\065\001\002\000\014\003\uffdf\011\uffdf" +
    "\012\uffdf\027\uffdf\031\uffdf\001\002\000\006\013\041\014" +
    "\042\001\002\000\010\003\067\013\041\014\042\001\002" +
    "\000\006\003\074\025\073\001\002\000\004\025\070\001" +
    "\002\000\004\030\071\001\002\000\004\026\014\001\002" +
    "\000\014\003\uffda\011\uffda\012\uffda\027\uffda\031\uffda\001" +
    "\002\000\006\003\077\030\100\001\002\000\004\030\075" +
    "\001\002\000\004\026\014\001\002\000\014\003\uffdb\011" +
    "\uffdb\012\uffdb\027\uffdb\031\uffdb\001\002\000\004\026\014" +
    "\001\002\000\006\003\101\026\014\001\002\000\014\003" +
    "\uffdd\011\uffdd\012\uffdd\027\uffdd\031\uffdd\001\002\000\014" +
    "\003\uffde\011\uffde\012\uffde\027\uffde\031\uffde\001\002\000" +
    "\014\003\uffdc\011\uffdc\012\uffdc\027\uffdc\031\uffdc\001\002" +
    "\000\004\025\105\001\002\000\004\030\106\001\002\000" +
    "\004\026\014\001\002\000\014\003\uffd9\011\uffd9\012\uffd9" +
    "\027\uffd9\031\uffd9\001\002\000\004\026\014\001\002\000" +
    "\006\003\112\026\014\001\002\000\010\003\uffd7\027\uffd7" +
    "\031\uffd7\001\002\000\010\003\uffd8\027\uffd8\031\uffd8\001" +
    "\002\000\010\003\uffd6\027\uffd6\031\uffd6\001\002\000\010" +
    "\003\uffe4\027\uffe4\031\uffe4\001\002\000\014\003\uffe0\011" +
    "\uffe0\012\uffe0\027\uffe0\031\uffe0\001\002\000\010\003\127" +
    "\013\041\014\042\001\002\000\010\003\uffcb\013\uffcb\014" +
    "\uffcb\001\002\000\010\003\uffce\013\uffce\014\uffce\001\002" +
    "\000\010\003\uffcf\013\uffcf\014\uffcf\001\002\000\010\003" +
    "\uffd0\013\uffd0\014\uffd0\001\002\000\010\003\uffcd\013\uffcd" +
    "\014\uffcd\001\002\000\010\003\uffcc\013\uffcc\014\uffcc\001" +
    "\002\000\006\003\uffd5\025\uffd5\001\002\000\006\003\uffd4" +
    "\025\uffd4\001\002\000\006\003\131\030\132\001\002\000" +
    "\004\026\014\001\002\000\006\003\133\026\014\001\002" +
    "\000\014\003\uffe1\011\062\012\060\027\uffe1\031\uffe1\001" +
    "\002\000\014\003\uffe1\011\062\012\060\027\uffe1\031\uffe1" +
    "\001\002\000\010\003\uffe9\027\uffe9\031\uffe9\001\002\000" +
    "\010\003\uffe8\027\uffe8\031\uffe8\001\002\000\014\003\uffe1" +
    "\011\062\012\060\027\uffe1\031\uffe1\001\002\000\010\003" +
    "\uffe7\027\uffe7\031\uffe7\001\002\000\004\025\142\001\002" +
    "\000\004\030\143\001\002\000\004\026\014\001\002\000" +
    "\014\003\uffe1\011\062\012\060\027\uffe1\031\uffe1\001\002" +
    "\000\010\003\uffe5\027\uffe5\031\uffe5\001\002\000\006\010" +
    "\030\013\032\001\002\000\022\002\ufff9\003\ufff9\010\030" +
    "\011\ufff9\012\ufff9\013\032\027\ufff9\031\ufff9\001\002\000" +
    "\016\002\ufffb\003\ufffb\011\ufffb\012\ufffb\027\ufffb\031\ufffb" +
    "\001\002\000\010\003\uffed\027\uffed\031\uffed\001\002\000" +
    "\010\003\uffee\027\uffee\031\uffee\001\002\000\010\003\037" +
    "\015\040\031\036\001\002\000\010\003\155\027\156\031" +
    "\146\001\002\000\006\010\030\013\032\001\002\000\016" +
    "\002\ufff8\003\ufff8\011\ufff8\012\ufff8\027\ufff8\031\ufff8\001" +
    "\002\000\006\003\162\031\161\001\002\000\016\003\ufff3" +
    "\005\ufff3\006\ufff3\007\ufff3\010\ufff3\013\ufff3\001\002\000" +
    "\016\003\ufff5\005\ufff5\006\ufff5\007\ufff5\010\ufff5\013\ufff5" +
    "\001\002\000\016\003\ufff4\005\ufff4\006\ufff4\007\ufff4\010" +
    "\ufff4\013\ufff4\001\002\000\004\002\ufffe\001\002\000\004" +
    "\002\001\001\002\000\004\026\014\001\002\000\004\002" +
    "\ufffc\001\002\000\004\025\170\001\002\000\004\026\014" +
    "\001\002\000\004\002\uffff\001\002\000\004\002\000\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\170\000\004\003\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\004\163\001\001\000\004\004\012\001" +
    "\001\000\002\001\001\000\010\005\022\007\016\010\014" +
    "\001\001\000\002\001\001\000\012\006\153\011\030\012" +
    "\023\013\026\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\006\025\007" +
    "\024\010\014\011\030\012\023\013\026\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\021\044\001\001\000\004\021\042" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\014\140" +
    "\021\050\001\001\000\006\014\047\021\050\001\001\000" +
    "\002\001\001\000\004\022\116\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\054\001\001\000\012\015" +
    "\056\016\055\017\060\020\062\001\001\000\006\017\114" +
    "\020\115\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\014\103\021\050\001\001\000\006\014\065\021\050\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\071\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\004\075\001\001\000\002" +
    "\001\001\000\004\004\102\001\001\000\004\004\101\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\004\106\001" +
    "\001\000\002\001\001\000\004\004\113\001\001\000\004" +
    "\004\112\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\021\125\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\004\136\001\001\000\004\004\133\001\001" +
    "\000\012\015\135\016\055\017\060\020\062\001\001\000" +
    "\012\015\134\016\055\017\060\020\062\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\015\137\016\055\017" +
    "\060\020\062\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\143\001\001\000\012\015" +
    "\144\016\055\017\060\020\062\001\001\000\002\001\001" +
    "\000\010\011\151\012\023\013\026\001\001\000\010\011" +
    "\150\012\023\013\026\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\011\150\012\023\013\026\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\165\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\004\170\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	public int errorNo = 0;
    public static void main(String[] args)
    {
        try{
            FileReader file = new FileReader(args[0]);
            Scanner scanner = new MPLexer(file);
            MPParser parser = new MPParser(scanner);
            parser.parse(); 
			if(parser.errorNo == 0)
				System.out.println("Analiza gotova. Nema gresaka u kodu.");
			else
				System.out.println("Analiza gotova. Broj gresaka u kodu: " + parser.errorNo);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
	
	public void syntax_error(Symbol cur_token)
	{
	
	}
	
	public void report_error(String message, Object info)
	{
		System.out.println(message);
	}
	
	public int getLine()
	{
		return ((MPLexer)getScanner()).getLine();
	}
	

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MPParser$actions {
  private final MPParser parser;

  /** Constructor */
  CUP$MPParser$actions(MPParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParser$result;

      /* select the action based on the action number */
      switch (CUP$MPParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // Assignment ::= ID error Term 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali :="); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Assignment*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // Assignment ::= ID ASSIGN error 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali Term"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Assignment*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // Assignment ::= ID ASSIGN Term 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Assignment*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // RelOp ::= MOREOREQUAL 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // RelOp ::= MORE 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // RelOp ::= NOTEQUAL 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // RelOp ::= EQUAL 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // RelOp ::= LESSOREQUAL 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // RelOp ::= LESS 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // Term ::= CONST 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // Term ::= ID 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // RelExpression ::= Term 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // RelExpression ::= Term RelOp error 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali drugi Term"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // RelExpression ::= Term RelOp Term 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // ElseStatement ::= ELSE error Block 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali :"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*ElseStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // ElseStatement ::= ELSE COLON error 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali blok deo else statement-a"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*ElseStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // ElseStatement ::= ELSE COLON Block 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*ElseStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Elif ::= ELIF error RelExpression RIGHTPAR COLON Block 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali ("); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*Elif*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Elif ::= ELIF LEFTPAR error RIGHTPAR COLON Block 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali RelExpression"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*Elif*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Elif ::= ELIF LEFTPAR RelExpression error COLON Block 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali )"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*Elif*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Elif ::= ELIF LEFTPAR RelExpression RIGHTPAR error Block 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali :"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*Elif*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Elif ::= ELIF LEFTPAR RelExpression RIGHTPAR COLON error 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali block deo u elif"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*Elif*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Elif ::= ELIF LEFTPAR RelExpression RIGHTPAR COLON Block 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*Elif*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // ElifList ::= Elif 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*ElifList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // ElifList ::= ElifList Elif 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*ElifList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // ElsePart ::= 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*ElsePart*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // ElsePart ::= ElseStatement 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*ElsePart*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // ElsePart ::= ElifList 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*ElsePart*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ElsePart ::= ElifList ElseStatement 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*ElsePart*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // IfStatement ::= IF error RelExpression RIGHTPAR COLON Block ElsePart 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali ("); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*IfStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // IfStatement ::= IF LEFTPAR error RIGHTPAR COLON Block ElsePart 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali RelExpression u zagradi"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*IfStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // IfStatement ::= IF LEFTPAR RelExpression RIGHTPAR error Block ElsePart 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali :"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*IfStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // IfStatement ::= IF LEFTPAR RelExpression RIGHTPAR COLON error ElsePart 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali block deo u if statement-u"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*IfStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // IfStatement ::= IF LEFTPAR RelExpression RIGHTPAR COLON Block ElsePart 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*IfStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Statement ::= IfStatement 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Statement ::= Assignment 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Statements ::= Statement 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*Statements*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Statements ::= Statements error Statement 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali ; posle Statements-a"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*Statements*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Statements ::= Statements SEMICOLON Statement 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*Statements*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Type ::= BOOLEAN 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Type ::= REAL 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Type ::= INT 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Variable ::= error ID SEMICOLON 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Nije naveden tip podataka"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*Variable*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Variable ::= Type error 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Nije naveden identifikator	"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*Variable*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Variable ::= Type ID error 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali ;"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*Variable*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Variable ::= Type ID SEMICOLON 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*Variable*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Variables ::= Variable 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*Variables*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Variables ::= Variables Variable 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*Variables*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Block ::= LEFTCURLYBR error Statements RIGHTCURLYBR 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Greska u deklaraciji promenljivih"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Block ::= LEFTCURLYBR Variables Statements error 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali }"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Block ::= LEFTCURLYBR Variables error RIGHTCURLYBR 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Greska u Statements"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Block ::= LEFTCURLYBR Variables Statements RIGHTCURLYBR 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Program ::= MAIN error RIGHTPAR Block 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali ()"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Program ::= MAIN LEFTPAR error Block 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fali )"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Program ::= MAIN LEFTPAR RIGHTPAR error 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Nekorektan Block u main-u"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= error LEFTPAR RIGHTPAR Block 
            {
              Object RESULT = null;
		System.out.println("Greska u liniji " + parser.getLine() + ": " + "Fli main kljucna rec"); parser.errorNo++;
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		RESULT = start_val;
              CUP$MPParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$MPParser$parser.done_parsing();
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Program ::= MAIN LEFTPAR RIGHTPAR Block 
            {
              Object RESULT = null;

              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

