
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 18 21:01:03 CET 2026
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.*;
import SymbolTable.*;

/** CUP v0.10k generated parser.
  * @version Sun Jan 18 21:01:03 CET 2026
  */
public class MPParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MPParser() {super();}

  /** Constructor which sets the default scanner. */
  public MPParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\045\000\002\007\006\000\002\002\004\000\002\024" +
    "\002\000\002\010\007\000\002\011\004\000\002\011\003" +
    "\000\002\013\005\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\012\005\000\002\012\003\000\002" +
    "\014\003\000\002\014\003\000\002\016\011\000\002\017" +
    "\004\000\002\017\003\000\002\017\003\000\002\017\002" +
    "\000\002\020\004\000\002\020\003\000\002\022\010\000" +
    "\002\021\005\000\002\005\005\000\002\005\003\000\002" +
    "\004\003\000\002\004\003\000\002\006\003\000\002\006" +
    "\003\000\002\006\003\000\002\023\003\000\002\023\003" +
    "\000\002\023\003\000\002\023\003\000\002\023\003\000" +
    "\002\023\003\000\002\015\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\004\010\005\001\002\000\004\002\101\001" +
    "\002\000\004\026\006\001\002\000\004\027\007\001\002" +
    "\000\004\030\011\001\002\000\004\002\001\001\002\000" +
    "\010\011\uffff\012\uffff\013\uffff\001\002\000\010\011\020" +
    "\012\015\013\016\001\002\000\004\007\077\001\002\000" +
    "\014\007\ufffc\011\ufffc\012\ufffc\013\ufffc\014\ufffc\001\002" +
    "\000\004\007\ufff9\001\002\000\004\007\ufff8\001\002\000" +
    "\014\007\027\011\020\012\015\013\016\014\025\001\002" +
    "\000\004\007\ufffa\001\002\000\006\031\ufff5\033\ufff5\001" +
    "\002\000\014\007\ufffd\011\ufffd\012\ufffd\013\ufffd\014\ufffd" +
    "\001\002\000\006\031\075\033\074\001\002\000\006\031" +
    "\ufff4\033\ufff4\001\002\000\004\026\037\001\002\000\006" +
    "\031\ufff6\033\ufff6\001\002\000\004\017\030\001\002\000" +
    "\012\004\032\005\034\006\036\007\031\001\002\000\024" +
    "\020\uffe8\021\uffe8\022\uffe8\023\uffe8\024\uffe8\025\uffe8\027" +
    "\uffe8\031\uffe8\033\uffe8\001\002\000\024\020\uffe6\021\uffe6" +
    "\022\uffe6\023\uffe6\024\uffe6\025\uffe6\027\uffe6\031\uffe6\033" +
    "\uffe6\001\002\000\006\031\uffdd\033\uffdd\001\002\000\024" +
    "\020\uffe4\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4\027" +
    "\uffe4\031\uffe4\033\uffe4\001\002\000\024\020\uffe7\021\uffe7" +
    "\022\uffe7\023\uffe7\024\uffe7\025\uffe7\027\uffe7\031\uffe7\033" +
    "\uffe7\001\002\000\024\020\uffe5\021\uffe5\022\uffe5\023\uffe5" +
    "\024\uffe5\025\uffe5\027\uffe5\031\uffe5\033\uffe5\001\002\000" +
    "\012\004\032\005\034\006\036\007\031\001\002\000\004" +
    "\027\052\001\002\000\020\020\047\021\045\022\044\023" +
    "\046\024\050\025\043\027\uffe9\001\002\000\012\004\032" +
    "\005\034\006\036\007\031\001\002\000\012\004\uffde\005" +
    "\uffde\006\uffde\007\uffde\001\002\000\012\004\uffe1\005\uffe1" +
    "\006\uffe1\007\uffe1\001\002\000\012\004\uffe2\005\uffe2\006" +
    "\uffe2\007\uffe2\001\002\000\012\004\uffe0\005\uffe0\006\uffe0" +
    "\007\uffe0\001\002\000\012\004\uffe3\005\uffe3\006\uffe3\007" +
    "\uffe3\001\002\000\012\004\uffdf\005\uffdf\006\uffdf\007\uffdf" +
    "\001\002\000\004\027\uffea\001\002\000\004\032\053\001" +
    "\002\000\004\030\011\001\002\000\012\015\060\016\057" +
    "\031\uffef\033\uffef\001\002\000\012\015\060\016\057\031" +
    "\ufff1\033\ufff1\001\002\000\006\031\ufff3\033\ufff3\001\002" +
    "\000\004\032\070\001\002\000\004\026\063\001\002\000" +
    "\006\031\ufff0\033\ufff0\001\002\000\012\015\uffed\016\uffed" +
    "\031\uffed\033\uffed\001\002\000\012\004\032\005\034\006" +
    "\036\007\031\001\002\000\004\027\065\001\002\000\004" +
    "\032\066\001\002\000\004\030\011\001\002\000\012\015" +
    "\uffec\016\uffec\031\uffec\033\uffec\001\002\000\004\030\011" +
    "\001\002\000\006\031\uffeb\033\uffeb\001\002\000\006\031" +
    "\ufff2\033\ufff2\001\002\000\012\015\uffee\016\uffee\031\uffee" +
    "\033\uffee\001\002\000\006\007\027\014\025\001\002\000" +
    "\014\002\ufffe\015\ufffe\016\ufffe\031\ufffe\033\ufffe\001\002" +
    "\000\006\031\ufff7\033\ufff7\001\002\000\004\033\100\001" +
    "\002\000\014\007\ufffb\011\ufffb\012\ufffb\013\ufffb\014\ufffb" +
    "\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\004\007\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\010\007\001\001" +
    "\000\002\001\001\000\004\024\011\001\001\000\010\003" +
    "\012\011\016\013\013\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\003" +
    "\012\012\022\013\021\014\025\015\020\016\023\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\004\032\006\034\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\004\040\005\037\006\034\001\001\000\002\001\001" +
    "\000\004\023\041\001\001\000\006\004\050\006\034\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\010\053\001\001" +
    "\000\012\017\055\020\054\021\060\022\061\001\001\000" +
    "\006\021\071\022\072\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\004\040\005\063\006\034\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\066\001\001\000" +
    "\002\001\001\000\004\010\070\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\014\075\015" +
    "\020\016\023\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MPParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MPParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MPParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

	symbolTable = new SymbolTable();

    }


	public int warnNo = 0;
	public int errNo = 0;
	SymbolTable symbolTable;
    public static void main(String[] args)
    {
        try{
            FileReader file = new FileReader(args[0]);
            java_cup.runtime.Scanner scanner = new MPLexer(file);
            MPParser parser = new MPParser(scanner);
            parser.parse();
			System.err.println("Analiza zavrsena. \nBroj upozorenja u kodu: " + parser.warnNo + "\nBroj gresaka u kodu: " + parser.errNo);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

	public void checkScopeWarnings(int level) 
	{
    	SymbolNode current = symbolTable.getVariables();
    	while (current != null) 
		{
        	Variable var = (Variable) current;
        
        	// Proveravamo samo promenljive nivoa koji se upravo zatvara
        	if (var.level == level) 
			{
            	if (var.last_def == -1 && var.last_use == -1) 
				{
                	System.err.println("Upozorenje: promenljiva " + var.name + " je deklarisana ali nema vrednost. [" + level + "]");
                	warnNo++;
            	}
            	else if (var.last_def > var.last_use) 
				{
                	System.err.println("Upozorenje: promenljiva " + var.name + " ima vrednost koja se ne koristi. [" + level + "]");
                	warnNo++;
            	}
        		current = current.next;
        	}
			else
				break;
    	}
	}

	public void syntax_error(Symbol cur_token)
	{

	}
	public int getLine()
	{
		return ((MPLexer) getScanner()).getLine();
	}	

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MPParser$actions {
  private final MPParser parser;

  /** Constructor */
  CUP$MPParser$actions(MPParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MPParser$do_action(
    int                        CUP$MPParser$act_num,
    java_cup.runtime.lr_parser CUP$MPParser$parser,
    java.util.Stack            CUP$MPParser$stack,
    int                        CUP$MPParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MPParser$result;

      /* select the action based on the action number */
      switch (CUP$MPParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Assignment ::= ID ASSIGN Term 
            {
              Object RESULT = null;
		int imeleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		

								Variable var = parser.symbolTable.getVar(ime);
								if(var == null)
								{
									System.err.println("Greska u liniji: " + parser.getLine() + " : promenljiva " + ime + " nije deklarisana.");
									parser.errNo++;
								} 
								else 
								{
									var.last_def = parser.getLine();
									
									boolean compatible = false;

									if(var.type.tkind == t.tkind)
									{
										compatible = true;
									}
									// Nizi u visi tip sme! int sme u real
									else if(var.type.tkind == Type.REAL && t.tkind == Type.INTEGER)
									{
										compatible = true;
										System.err.println("Izvrsena implicitna konverzija iz INT u REAL!");
									}

									if(compatible)
									{
										var.last_def = parser.getLine();
               							var.isInitialized = true;
									}
									else
									{
										System.err.println("Greska u liniji " + parser.getLine() + ": Nekompatibilni tipovi u dodeli za '" + ime + "'.");
                						parser.errNo++;
									}
								}

								System.out.println( "Redukcija 32: Assignment ::= ID := Term" );
							
              CUP$MPParser$result = new java_cup.runtime.Symbol(11/*Assignment*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // RelOp ::= MOREOREQUAL 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 31: RelOp ::= >=" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(17/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // RelOp ::= MORE 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 30: RelOp ::= >" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(17/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // RelOp ::= NOTEQUAL 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 29: RelOp ::= <>" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(17/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // RelOp ::= EQUAL 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 28: RelOp ::= ==" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(17/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // RelOp ::= LESSOREQUAL 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 27: RelOp ::= <=" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(17/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // RelOp ::= LESS 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 26: RelOp ::= <" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(17/*RelOp*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Konstanta ::= REALCONST 
            {
              Constant RESULT = null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Double c = (Double)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
							System.out.println( "Redukcija konstante: Konstanta ::= REALCONST" );
							RESULT = new Constant(parser.symbolTable.getType("real"), c);
						
              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*Konstanta*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // Konstanta ::= BOOLCONST 
            {
              Constant RESULT = null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Boolean c = (Boolean)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
							System.out.println( "Redukcija konstante: Konstanta ::= BOOLCONST" );
							RESULT = new Constant(parser.symbolTable.getType("boolean"), c);
						
              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*Konstanta*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // Konstanta ::= INTCONST 
            {
              Constant RESULT = null;
		int cleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
							System.out.println( "Redukcija konstante: Konstanta ::= INTCONST" );
							RESULT = new Constant(parser.symbolTable.getType("int"), c);
						
              CUP$MPParser$result = new java_cup.runtime.Symbol(4/*Konstanta*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Term ::= Konstanta 
            {
              Type RESULT = null;
		int kleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Constant k = (Constant)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
						RESULT = k.type;
						System.out.println( "Redukcija 25: Term ::= Konstanta" );
					
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Term ::= ID 
            {
              Type RESULT = null;
		int imeleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
				Variable var = parser.symbolTable.getVar(ime);
				if(var == null)
				{
					System.err.println("Greska u liniji: " + parser.getLine() + " : promenljiva " + ime + " nije deklarisana.");
					RESULT = parser.symbolTable.getType("unknown");
					parser.errNo++;
				} 
				else 
				{
					if(!var.isInitialized)
					{
						System.err.println("Greska u liniji " + parser.getLine() + ": Promenljiva '" + ime + "' nije inicijalizovana.");
                		parser.errNo++;
					}
					var.last_use = parser.getLine();
					RESULT = var.type;
				}
				System.out.println( "Redukcija 24: Term ::= ID" );
			
              CUP$MPParser$result = new java_cup.runtime.Symbol(2/*Term*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // RelExpression ::= Term 
            {
              Type RESULT = null;
		int tleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
						if(t.tkind != Type.BOOLEAN)
						{
							RESULT = parser.symbolTable.getType("unknown");
							System.err.println( "Greska u liniji: " + parser.getLine() + " : Uslov mora biti boolean tipa!" );
							parser.errNo++;
						}
						else
						{
							RESULT = parser.symbolTable.getType("boolean");
						}
						System.out.println( "Redukcija 23: RelExpression ::= Term" );
					
              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // RelExpression ::= Term RelOp Term 
            {
              Type RESULT = null;
		int t1left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		Type t1 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int t2left = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left;
		int t2right = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right;
		Type t2 = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).value;
		
									boolean t1Num = (t1.tkind == Type.INTEGER || t1.tkind == Type.REAL);
        							boolean t2Num = (t2.tkind == Type.INTEGER || t2.tkind == Type.REAL);

									if(!t1Num || !t2Num)
									{
										System.err.println("Greska u liniji: " + parser.getLine() + " : Relacioni operatori se mogu primeniti samo nad numerickim podacima!");
										parser.errNo++;
										RESULT = parser.symbolTable.getType("unknown");
									}
									else
									{
										RESULT = parser.symbolTable.getType("boolean");
									}
									System.out.println( "Redukcija 22: RelExpression ::= Term RelOp Term" );
								
              CUP$MPParser$result = new java_cup.runtime.Symbol(3/*RelExpression*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // ElseStatement ::= ELSE COLON Block 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 21: ElseStatement ::= else : Block" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(15/*ElseStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Elif ::= ELIF LEFTPAR RelExpression RIGHTPAR COLON Block 
            {
              Object RESULT = null;
		int releft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left;
		int reright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).right;
		Type re = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).value;
		
															if(re.tkind != Type.BOOLEAN) 
															{
        													    System.err.println("Greska u liniji " + parser.getLine() + ": Uslov u ELIF naredbi mora biti boolean!");
        										   				parser.errNo++;
      														}
															System.out.println( "Redukcija 20: Elif ::= elif(RelExpression) : Block" );
														
              CUP$MPParser$result = new java_cup.runtime.Symbol(16/*Elif*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // ElifList ::= Elif 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 19: ElifList ::= Elif" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*ElifList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // ElifList ::= ElifList Elif 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 18: ElifList ::= ElifList Elif" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(14/*ElifList*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ElsePart ::= 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 17: ElsePart ::= Epsilon" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*ElsePart*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ElsePart ::= ElseStatement 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 16: ElsePart ::= ElseStatement" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*ElsePart*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // ElsePart ::= ElifList 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 15: ElsePart ::= ElifList" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*ElsePart*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ElsePart ::= ElifList ElseStatement 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 14: ElsePart ::= ElifList ElseStatement" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(13/*ElsePart*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // IfStatement ::= IF LEFTPAR RelExpression RIGHTPAR COLON Block ElsePart 
            {
              Object RESULT = null;
		int releft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-4)).left;
		int reright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-4)).right;
		Type re = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-4)).value;
		
																		if(re.tkind != Type.BOOLEAN) 
																		{
            																System.err.println("Greska u liniji " + parser.getLine() + ": Uslov u IF naredbi mora biti boolean!");
            																parser.errNo++;
        																}
																		System.out.println( "Redukcija 13: IfStatement ::= if (RelExpression) : Block ElsePart" );
																	
              CUP$MPParser$result = new java_cup.runtime.Symbol(12/*IfStatement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-6)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Statement ::= IfStatement 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 12: Statement ::= IfStatement" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Statement ::= Assignment 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 11: Statement ::= Assignment" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(10/*Statement*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Statements ::= Statement 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 10: Statements ::= Statement" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Statements*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Statements ::= Statements SEMICOLON Statement 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 9: Statements ::= Statements ; Statement" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(8/*Statements*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Type ::= BOOLEAN 
            {
              Type RESULT = null;
		
					RESULT = parser.symbolTable.getType("boolean");
					System.out.println( "Redukcija 8: Type ::= BOOLEAN" );
				
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Type ::= REAL 
            {
              Type RESULT = null;
		
				RESULT = parser.symbolTable.getType("real");
				System.out.println( "Redukcija 7: Type ::= REAL" );
			
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Type ::= INT 
            {
              Type RESULT = null;
		
				RESULT = parser.symbolTable.getType("int");
				System.out.println( "Redukcija 6: Type ::= INT" );
			
              CUP$MPParser$result = new java_cup.runtime.Symbol(1/*Type*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Variable ::= Type ID SEMICOLON 
            {
              Object RESULT = null;
		int tleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).value;
		int imeleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int imeright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		String ime = (String)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		
										System.out.println( "Redukcija 5: Variable ::= Type ID" );
										if(!parser.symbolTable.addVar(ime, t))
										{
											System.err.println("Greska u liniji:" + parser.getLine() + ": " + "Promenljiva " + ime + " je vec deklarisana!");
											parser.errNo++;
										}
								
              CUP$MPParser$result = new java_cup.runtime.Symbol(9/*Variable*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Variables ::= Variable 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 4: Variables ::= Variable" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*Variables*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Variables ::= Variables Variable 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 3: Variables ::= Variables Variable" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(7/*Variables*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Block ::= LEFTCURLYBR NT$0 Variables Statements RIGHTCURLYBR 
            {
              Object RESULT = null;
              // propagate RESULT from NT$0
              if ( ((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).value != null )
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).value;
		 parser.checkScopeWarnings(parser.symbolTable.getCurrentLevel()); parser.symbolTable.exitScope(); 
			System.out.println( "Redukcija 2: Block ::= { Variables Statements }" );
		 
              CUP$MPParser$result = new java_cup.runtime.Symbol(6/*Block*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // NT$0 ::= 
            {
              Object RESULT = null;
 parser.symbolTable.enterScope(); 
              CUP$MPParser$result = new java_cup.runtime.Symbol(18/*NT$0*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).value;
		RESULT = start_val;
              CUP$MPParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$MPParser$parser.done_parsing();
          return CUP$MPParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Program ::= MAIN LEFTPAR RIGHTPAR Block 
            {
              Object RESULT = null;
		System.out.println( "Redukcija 1: Program ::= main ( ) Block" );
              CUP$MPParser$result = new java_cup.runtime.Symbol(5/*Program*/, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$MPParser$stack.elementAt(CUP$MPParser$top-0)).right, RESULT);
            }
          return CUP$MPParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

