
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 18 21:01:03 CET 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHTCURLYBR = 23;
  public static final int LEFTCURLYBR = 22;
  public static final int SEMICOLON = 25;
  public static final int ELSE = 12;
  public static final int INT = 7;
  public static final int EQUAL = 16;
  public static final int NOTEQUAL = 17;
  public static final int LEFTPAR = 20;
  public static final int MOREOREQUAL = 19;
  public static final int INTCONST = 2;
  public static final int RIGHTPAR = 21;
  public static final int IF = 10;
  public static final int COLON = 24;
  public static final int ID = 5;
  public static final int LESSOREQUAL = 15;
  public static final int BOOLEAN = 9;
  public static final int EOF = 0;
  public static final int MORE = 18;
  public static final int REALCONST = 3;
  public static final int MAIN = 6;
  public static final int ELIF = 11;
  public static final int error = 1;
  public static final int ASSIGN = 13;
  public static final int REAL = 8;
  public static final int LESS = 14;
  public static final int BOOLCONST = 4;
}

